const message = {
    INVALID_USERNAME : "Tên tài khoản phải có độ dài tối thiểu là 5, tối đa là 20 ký tự chữ hoặc số",
    NOT_ACTIVE : "Tài khoản của bạn chưa được kích hoạt. Vui lòng kiểm tra email hoặc nhập mã kích hoạt.",
    ACTIVE_FAILED : "Kích hoạt tài khoản không thành công",
    INVALID_PASSWORD : "Mật khẩu tối thiểu phải là 8 ký tự",
    INVALID_EMAIL : "Email phải định dạng là xxx@yyy.zz",
    USERNAME_EXISTS : "Tên tài khoản đã tồn tại",
    EMAIL_EXISTS : "Email đã được sử dụng",
    SUCCESS : "Success",
    ERROR : "Có lỗi xảy ra. Vui lòng thử lại!",
    WRONG_USER : "Tên tài khoản hoặc mật khẩu không đúng!",
    USER_NOT_EXISTS : "Tài khoản này không tồn tại trên hệ thống",
    INVALID_TOKEN : "Invalid token",
    UPDATE_FAILED : "Cập nhật thông tin không thành công",
    WRONG_OLD_PASSWORD : "Mật khẩu cũ không đúng",
    ERROR_ACTIVE : "Active phải là 0 hoặc 1",
    CAR_EXISTS : "Xe này đã tồn tại",
    ERROR_TYPE_FOLLOW : "type phải là follower hoặc following",
    EXISTS_FOLLOW : "Đã follow",
    NOT_EXISTS_USER_IN_TRAVEL : "User không tồn tại trong travel",
    NOT_ACCESS : "Không có quyền thao tác!",
    EXISTS_VOTE : "Đã đánh giá",
    NOT_EXISTS_VOTE : "Không tồn tại đánh giá",
    WRONG_RESET_CODE : "Sai reset code",
    EXISTS_LIKE : "Đã like",
    NOT_EXISTS_ENUM : 'Không tồn tại Enum. Enum gồm: ',
    VALID_DATETIME : "Sai định dạng ngày tháng thời gian YYYY-MM-DD HH:mm:ss",
}

module.exports = message